/**
 * JS port of src/utils.py (the parts the letters pipeline needs).
 *
 * PARITY RULE: normalizeLandmarks must produce EXACTLY what the Python
 * normalize_landmarks produces — the model was trained on Python's output.
 * Any change here must keep web/js/utils.test.html (which replays fixtures
 * generated by tools/make_fixtures.py from real capture data) fully green.
 */

const WRIST = 0;       // wrist landmark (origin)
const MIDDLE_MCP = 9;  // base of the middle finger (scale reference)

/**
 * Normalize one 63-value hand sample (21 landmarks x (x, y, z)).
 * Port of src/utils.py::_normalize_single:
 *   1. undo MediaPipe's per-axis stretch when `aspect` (frame width/height)
 *      is given: y /= aspect, x and z untouched ("width units" — MediaPipe
 *      normalizes x by frame width, y by frame height, z scales like x, so
 *      a 9:16 portrait phone otherwise yields a differently-stretched vector
 *      than the 16:9 training data). Must happen BEFORE centering/scaling.
 *   2. center the 21 points on the wrist
 *   3. scale by the wrist -> middle-MCP distance (guard: < 1e-6 -> 1.0)
 * `aspect` undefined/null skips step 1 (legacy behavior).
 */
export function normalizeLandmarks(flat, aspect) {
  if (flat.length !== 63) {
    throw new Error(`Expected 63 values, got ${flat.length}`);
  }
  let src = flat;
  if (aspect !== undefined && aspect !== null) {
    // Float32Array mirrors Python's float32 rounding after the division,
    // keeping the parity fixtures within tolerance.
    src = new Float32Array(63);
    for (let i = 0; i < 21; i++) {
      src[i * 3] = flat[i * 3];
      src[i * 3 + 1] = flat[i * 3 + 1] / aspect;
      src[i * 3 + 2] = flat[i * 3 + 2];
    }
  }
  const out = new Float32Array(63);
  const wx = src[WRIST * 3], wy = src[WRIST * 3 + 1], wz = src[WRIST * 3 + 2];
  for (let i = 0; i < 21; i++) {
    out[i * 3] = src[i * 3] - wx;
    out[i * 3 + 1] = src[i * 3 + 1] - wy;
    out[i * 3 + 2] = src[i * 3 + 2] - wz;
  }
  let scale = Math.hypot(
    out[MIDDLE_MCP * 3], out[MIDDLE_MCP * 3 + 1], out[MIDDLE_MCP * 3 + 2],
  );
  if (scale < 1e-6) scale = 1.0;
  for (let i = 0; i < 63; i++) out[i] /= scale;
  return out;
}

/**
 * Sliding-window vote filter. Port of src/utils.py::PredictionSmoother.
 * null predictions count AGAINST stability on purpose: if the hand leaves
 * the frame the system waits for fresh consensus.
 */
export class PredictionSmoother {
  constructor(window = 7, minVotes = 5) {
    this._buffer = [];
    this._window = window;
    this._minVotes = minVotes;
  }

  update(prediction) {
    this._buffer.push(prediction);
    if (this._buffer.length > this._window) this._buffer.shift();
  }

  getStable() {
    const valid = this._buffer.filter((p) => p !== null && p !== undefined);
    if (valid.length === 0) return null;
    const counts = new Map();
    let top = null, topCount = 0;
    for (const p of valid) {
      const n = (counts.get(p) || 0) + 1;
      counts.set(p, n);
      if (n > topCount) { top = p; topCount = n; }
    }
    return topCount >= this._minVotes ? top : null;
  }

  reset() {
    this._buffer.length = 0;
  }
}

/**
 * Spelled-letters strip. Port of src/overlay.py::LetterBuffer, minus
 * del/space handling: the letters model has 24 classes (A-Y, no J/Z) and no
 * del/space classes, so the web UI uses a clear button instead.
 * Same cadence rule: once a letter is accepted, nothing else is accepted
 * until cooldownFrames pass (a held pose repeats every ~0.67s, not per frame).
 */
export class LetterBuffer {
  constructor(cooldownFrames) {
    this._chars = [];
    this._cooldown = 0;
    this._cooldownFrames = cooldownFrames;
  }

  /** Offer the current stable letter (or null). True if accepted this frame. */
  update(letter) {
    if (this._cooldown > 0) this._cooldown--;
    if (letter === null || letter === undefined || this._cooldown > 0) {
      return false;
    }
    this._chars.push(letter.toUpperCase());
    this._cooldown = this._cooldownFrames;
    return true;
  }

  getText(maxChars = 28) {
    return this._chars.slice(-maxChars).join("");
  }

  clear() {
    this._chars.length = 0;
    this._cooldown = 0;
  }
}
