/**
 * JS port of src/utils.py (the parts the letters pipeline needs).
 *
 * PARITY RULE: normalizeLandmarks must produce EXACTLY what the Python
 * normalize_landmarks produces — the model was trained on Python's output.
 * Any change here must keep web/js/utils.test.html (which replays fixtures
 * generated by tools/make_fixtures.py from real capture data) fully green.
 */

const WRIST = 0;       // wrist landmark (origin)
const MIDDLE_MCP = 9;  // base of the middle finger (scale reference)

/**
 * Normalize one 63-value hand sample (21 landmarks x (x, y, z)).
 * Port of src/utils.py::_normalize_single:
 *   1. undo MediaPipe's per-axis stretch when `aspect` (frame width/height)
 *      is given: y /= aspect, x and z untouched ("width units" — MediaPipe
 *      normalizes x by frame width, y by frame height, z scales like x, so
 *      a 9:16 portrait phone otherwise yields a differently-stretched vector
 *      than the 16:9 training data). Must happen BEFORE centering/scaling.
 *   2. center the 21 points on the wrist
 *   3. scale by the wrist -> middle-MCP distance (guard: < 1e-6 -> 1.0)
 * `aspect` undefined/null skips step 1 (legacy behavior).
 */
// Scratch for the un-stretch step: the per-frame path calls this dozens of
// times per second, so the intermediate must not allocate. Only valid within
// one call (never returned, never stored).
const _normSrcScratch = new Float32Array(63);

export function normalizeLandmarks(flat, aspect, out) {
  if (flat.length !== 63) {
    throw new Error(`Expected 63 values, got ${flat.length}`);
  }
  let src = flat;
  if (aspect !== undefined && aspect !== null) {
    // Float32Array mirrors Python's float32 rounding after the division,
    // keeping the parity fixtures within tolerance.
    src = _normSrcScratch;
    for (let i = 0; i < 21; i++) {
      src[i * 3] = flat[i * 3];
      src[i * 3 + 1] = flat[i * 3 + 1] / aspect;
      src[i * 3 + 2] = flat[i * 3 + 2];
    }
  }
  // `out` (optional) lets the hot path reuse a destination buffer; omitted,
  // behavior is identical to the original allocate-and-return.
  const dst = out || new Float32Array(63);
  const wx = src[WRIST * 3], wy = src[WRIST * 3 + 1], wz = src[WRIST * 3 + 2];
  for (let i = 0; i < 21; i++) {
    dst[i * 3] = src[i * 3] - wx;
    dst[i * 3 + 1] = src[i * 3 + 1] - wy;
    dst[i * 3 + 2] = src[i * 3 + 2] - wz;
  }
  let scale = Math.hypot(
    dst[MIDDLE_MCP * 3], dst[MIDDLE_MCP * 3 + 1], dst[MIDDLE_MCP * 3 + 2],
  );
  if (scale < 1e-6) scale = 1.0;
  for (let i = 0; i < 63; i++) dst[i] /= scale;
  return dst;
}

/**
 * Sliding-window vote filter over TIME, not frames (deliberate web divergence
 * from src/utils.py::PredictionSmoother, 2026-07-19: frame counts made slow
 * devices wait proportionally longer in wall-clock time). Semantics preserved:
 * null predictions count AGAINST stability on purpose — if the hand leaves the
 * frame the system waits for fresh consensus.
 *
 * The vote requirement is a FRACTION of however many samples landed inside the
 * window (5-of-7 at 30fps, 10-of-14 at 60fps: the same ~170ms of agreement),
 * with an absolute floor so one or two stray frames can never look "stable".
 * `nowMs` is an explicit parameter (the frame timestamp) so tests are
 * deterministic and the class never reads a clock.
 */
export class TimeSmoother {
  constructor(windowMs, minFraction, minSamples) {
    this._window = windowMs;
    this._minFraction = minFraction;
    this._minSamples = minSamples;
    this._buf = [];            // { p: prediction|null, t: ms }
    this._counts = new Map();  // reused across calls — no per-frame allocation
  }

  update(prediction, nowMs) {
    this._buf.push({ p: prediction, t: nowMs });
    const cutoff = nowMs - this._window;
    while (this._buf.length && this._buf[0].t <= cutoff) this._buf.shift();
  }

  getStable() {
    const n = this._buf.length;
    if (n < this._minSamples) return null;
    // The tiny epsilon keeps float error in fraction*n (e.g. 5/7 * 7) from
    // ever ceiling one vote above the intended integer.
    const need = Math.max(this._minSamples, Math.ceil(this._minFraction * n - 1e-9));
    this._counts.clear();
    let top = null, topCount = 0;
    for (const e of this._buf) {
      if (e.p === null || e.p === undefined) continue;
      const c = (this._counts.get(e.p) || 0) + 1;
      this._counts.set(e.p, c);
      if (c > topCount) { top = e.p; topCount = c; }
    }
    return topCount >= need ? top : null;
  }

  reset() {
    this._buf.length = 0;
  }
}

/**
 * Accumulated-characters strip for the static modes (letters, numbers), with
 * the desktop's word-close behavior (src/overlay.py::LetterBuffer): the models
 * have no del/space classes, so a fingerspelled word ends via the Space button
 * (`space()`) or a pause with no new letter (`maybeAutoClose()`). Closed words
 * queue in `_completed` for the caller to drain (`popCompletedWords()`) into
 * voice/log — same decoupling as the desktop.
 *
 * Time-based (web divergence, 2026-07-19): the accept cooldown is a ms
 * deadline, not a frame countdown, so a held pose repeats at the same
 * real-time pace on every device. `_chars` is capped (old chars drop off the
 * front) — unbounded growth was a slow session-long leak.
 */
export class CharBuffer {
  constructor(cooldownMs, wordCloseMs, maxChars) {
    this._cooldownMs = cooldownMs;
    this._wordCloseMs = wordCloseMs;
    this._maxChars = maxChars;
    this._chars = [];
    this._completed = [];
    this._readyAt = 0;         // next accept allowed at (ms)
    this._lastAcceptAt = null; // ms of last accepted char; null = no open word
  }

  /** Offer the current stable character (or null). True if accepted this frame. */
  update(ch, nowMs) {
    if (ch === null || ch === undefined || nowMs < this._readyAt) {
      return false;
    }
    this._chars.push(ch.toUpperCase());
    if (this._chars.length > this._maxChars) {
      this._chars.splice(0, this._chars.length - this._maxChars);
    }
    this._readyAt = nowMs + this._cooldownMs;
    this._lastAcceptAt = nowMs;
    return true;
  }

  /** Manual word close (Space button). Returns the closed word, or null. */
  space() {
    const word = this._closeWord();
    // A deliberate user action must not be swallowed by the letter cooldown.
    this._readyAt = 0;
    this._lastAcceptAt = null;
    return word;
  }

  /**
   * Auto-close on inactivity: once no letter has been accepted for
   * wordCloseMs, the in-progress word is finished. Call every frame; returns
   * the closed word on the closing frame, else null.
   */
  maybeAutoClose(nowMs) {
    if (this._lastAcceptAt === null) return null;
    if (nowMs - this._lastAcceptAt < this._wordCloseMs) return null;
    const word = this._closeWord();
    this._lastAcceptAt = null;
    return word;
  }

  /** Extract the trailing word, queue it, append the separating space. */
  _closeWord() {
    if (this._chars.length === 0 || this._chars[this._chars.length - 1] === " ") {
      return null;
    }
    const text = this._chars.join("").replace(/\s+$/, "");
    const parts = text.split(/\s+/);
    const word = parts[parts.length - 1] || null;
    if (word) this._completed.push(word);
    this._chars.push(" ");
    return word;
  }

  /** Drain finished words (for voice/log) — decouples buffer from consumers. */
  popCompletedWords() {
    if (this._completed.length === 0) return this._completed;
    const done = this._completed;
    this._completed = [];
    return done;
  }

  getText(maxChars = 28) {
    return this._chars.slice(-maxChars).join("");
  }

  clear() {
    this._chars.length = 0;
    this._completed.length = 0;
    this._readyAt = 0;
    this._lastAcceptAt = null;
  }
}

// ===========================================================================
// WORD pipeline (dynamic signs) — ports of src/utils.py's word helpers and the
// desktop word-mode glue. PARITY RULE applies here too: buildWordFeatures /
// wordFeaturesFromRaw / resampleSequence must match Python exactly (gated by
// web/fixtures/words/*). Letters/numbers do not use any of this.
// ===========================================================================

export const WORD_FEATURE_LEN = 130;    // src.utils.WORD_FEATURE_LEN
export const WORD_RAW_FRAME_LEN = 131;  // src.utils.WORD_RAW_FRAME_LEN
const _HAND_BLOCK_LEN = 65;             // 63 shape + 2 body-relative wrist pos

// Scratch for one normalized handshape while filling a feature row (valid only
// within _handBlockInto; distinct from normalizeLandmarks' own src scratch).
const _handNormScratch = new Float32Array(63);

/**
 * Write one hand's 65-value block into `target` at `offset`. Port of
 * src/utils.py::_hand_block. `handFlat` is a 63-value raw landmark array or
 * null; `frame` is [cx, cy, scale] in width units or null (no body anchor);
 * `aspect` un-stretches. The target block must already be zeroed: missing hand
 * -> zeros stay; no body frame -> position part stays 0 (never the raw
 * on-screen coordinate — that would leak absolute position).
 */
function _handBlockInto(target, offset, handFlat, frame, aspect) {
  if (handFlat === null || handFlat === undefined) return; // zeros = absent
  normalizeLandmarks(handFlat, aspect, _handNormScratch);  // 63 handshape
  for (let i = 0; i < 63; i++) target[offset + i] = _handNormScratch[i];
  if (frame !== null) {
    const [cx, cy, scale] = frame;
    target[offset + 63] = (handFlat[0] - cx) / scale;          // raw wrist x
    target[offset + 64] = (handFlat[1] / aspect - cy) / scale; // raw wrist y (un-stretched)
  }
}

/**
 * Full (130,) body-anchored two-hand word feature for one frame.
 * Port of src/utils.py::build_word_features. `aspect` is MANDATORY (same as
 * Python) so a forgotten call site fails loudly instead of silently
 * reintroducing the per-axis geometry bug. `out` (optional) reuses a
 * destination row — the live pipeline recycles rows through a pool; omitted,
 * a fresh zeroed array is allocated (identical results either way).
 */
export function buildWordFeatures(leftHand, rightHand, shoulderL, shoulderR, aspect, out) {
  if (aspect === undefined || aspect === null) {
    throw new Error("buildWordFeatures requires the frame aspect ratio (width/height).");
  }
  // Body frame in WIDTH UNITS: un-stretch every y before any geometry, so the
  // anchor (center + shoulder-width scale) is camera-orientation invariant.
  let frame = null;
  if (shoulderL && shoulderR) {
    const cx = (shoulderL[0] + shoulderR[0]) * 0.5;
    const cy = (shoulderL[1] / aspect + shoulderR[1] / aspect) * 0.5;
    let scale = Math.hypot(shoulderL[0] - shoulderR[0],
                           (shoulderL[1] - shoulderR[1]) / aspect);
    if (scale < 1e-6) scale = 1.0;
    frame = [cx, cy, scale];
  }
  const dst = out || new Float32Array(WORD_FEATURE_LEN);
  if (out) dst.fill(0); // pooled rows carry old data; fresh arrays are zeroed
  _handBlockInto(dst, 0, leftHand, frame, aspect);
  _handBlockInto(dst, _HAND_BLOCK_LEN, rightHand, frame, aspect);
  return dst;
}

/**
 * Turn one stored raw capture row (131) back into a (130) feature vector.
 * Port of src/utils.py::word_features_from_raw. All-zero blocks map to
 * null/absent (MediaPipe never emits an exact all-zero block).
 */
export function wordFeaturesFromRaw(row) {
  if (row.length !== WORD_RAW_FRAME_LEN) {
    throw new Error(`Raw word frame must have ${WORD_RAW_FRAME_LEN} values, got ${row.length}.`);
  }
  const anyNonZero = (a, lo, hi) => {
    for (let i = lo; i < hi; i++) if (a[i] !== 0) return true;
    return false;
  };
  const left  = anyNonZero(row, 0, 63)    ? row.slice(0, 63)   : null;
  const right = anyNonZero(row, 63, 126)  ? row.slice(63, 126) : null;
  const shL   = anyNonZero(row, 126, 128) ? [row[126], row[127]] : null;
  const shR   = anyNonZero(row, 128, 130) ? [row[128], row[129]] : null;
  return buildWordFeatures(left, right, shL, shR, row[130]);
}

/**
 * numpy-compatible round (half-to-even). Math.round rounds .5 toward +Inf,
 * which would disagree with np.round at exact half-integers; resampleSequence
 * relies on matching numpy's index picking, so use half-to-even here.
 */
function npRound(x) {
  const floor = Math.floor(x);
  const diff = x - floor;
  if (diff < 0.5) return floor;
  if (diff > 0.5) return floor + 1;
  return floor % 2 === 0 ? floor : floor + 1; // exactly .5 -> nearest even
}

/**
 * Resample a list of equal-length frame rows to exactly `n`, evenly spaced.
 * Port of src/utils.py::resample_sequence (np.linspace(0, len-1, n).round()).
 * Index-picking (no interpolation), so it commutes with per-frame featurization.
 */
export function resampleSequence(frames, n) {
  const len = frames.length;
  if (len === 0) throw new Error("Cannot resample an empty sequence.");
  const out = new Array(n);
  for (let i = 0; i < n; i++) {
    const pos = n === 1 ? 0 : (len - 1) * i / (n - 1);
    out[i] = frames[npRound(pos)];
  }
  return out;
}

/**
 * Mean over feature dims of the per-dim std of the last `window` frames.
 * Port of the motion test in src/classifier.py::_run_words (population std,
 * numpy default ddof=0). Used to decide whether the hand is actively signing.
 */
export function sequenceMotion(frames, window) {
  // Index arithmetic instead of .slice(-window): same math, no per-call copy
  // (this runs every frame in word mode).
  const T = Math.min(window, frames.length);
  if (T === 0) return 0;
  const base = frames.length - T;
  const D = frames[base].length;
  let total = 0;
  for (let d = 0; d < D; d++) {
    let mean = 0;
    for (let t = 0; t < T; t++) mean += frames[base + t][d];
    mean /= T;
    let variance = 0;
    for (let t = 0; t < T; t++) { const diff = frames[base + t][d] - mean; variance += diff * diff; }
    total += Math.sqrt(variance / T);
  }
  return total / D;
}

/**
 * Vote -> confirm -> repeat-guard state machine for dynamic word signs.
 * Owns a PredictionSmoother plus a guard clock (seconds). step() returns
 * { word, confidence, isNew }; isNew is true only on the frame a fresh sign is
 * committed (the moment to append/speak it).
 *
 * DELIBERATE DIVERGENCE from main.py::WordCommitFSM (web-only, 2026-07-18):
 * the desktop FSM blocks EVERY commit for cooldownSeconds after a sign, so the
 * user waits out a dead time between signs and cannot hold a conversation at
 * speaking pace. Here the guard blocks only a REPEAT of the sign just
 * committed:
 *
 *   - A DIFFERENT sign commits immediately  -> WANT -> DRINK -> NOW chains fast.
 *   - The SAME sign held commits exactly ONCE (the desktop re-fired it every
 *     cooldown window), and may be signed again after it is released.
 *   - cooldownSeconds is no longer a lock-out: it is the display hold (how long
 *     the sign stays on the HUD) and the release debounce (how long the sign
 *     must be gone before the same one counts as new), so a brief detection gap
 *     mid-sign cannot duplicate a word.
 *
 * The smoother is deliberately NOT reset on commit: its votes for the incoming
 * sign keep accumulating, which is what lets the next distinct sign land fast.
 * Jitter protection therefore rests entirely on the smoother's vote demand
 * rather than on a dead time — raise WORD_SMOOTH_MIN_FRACTION if spurious
 * words appear.
 */
export class WordCommitFSM {
  constructor(smoother, cooldownSeconds) {
    this._smoother = smoother;
    this._cooldown = cooldownSeconds;
    this.reset();
  }

  reset() {
    this._smoother.reset();
    this._locked = null;
    this._lockedConf = 0.0;
    this._cooldownUntil = 0.0;
    this._lastWord = null;  // sign holding the repeat guard (null = guard open)
  }

  /** @param wordPred {prediction,confidence}|null  @param now seconds */
  step(wordPred, now) {
    // The FSM clock is in seconds (parity with main.py); the TimeSmoother
    // takes milliseconds — the only line that bridges the two.
    this._smoother.update(wordPred ? wordPred.prediction : null, now * 1000);
    const stable = this._smoother.getStable();

    if (stable !== null) {
      if (stable !== this._lastWord) {
        // Different from the sign under guard -> commit right away.
        this._lastWord = stable;
        this._locked = stable;
        this._lockedConf = wordPred ? wordPred.confidence : 0.0;
        this._cooldownUntil = now + this._cooldown;
        return { word: stable, confidence: this._lockedConf, isNew: true };
      }
      // Same sign still being held: keep it on screen, do not re-commit.
      return { word: this._locked, confidence: this._lockedConf, isNew: false };
    }

    // No stable sign (released, or mid-transition between two signs).
    if (now < this._cooldownUntil) {
      // Inside the hold window: keep showing the sign AND keep the guard armed,
      // so a momentary detection gap does not re-commit the same word.
      return { word: this._locked, confidence: this._lockedConf, isNew: false };
    }
    this._locked = null;
    this._lastWord = null;  // released long enough -> the same sign may repeat
    return { word: null, confidence: 0.0, isNew: false };
  }
}

/**
 * Running sentence of recognized signs. Port of src/overlay.py::WordBuffer,
 * time-based (web divergence, 2026-07-19): the sentence auto-clears after
 * pauseMs with no new sign (just pause to start fresh) — a wall-clock pause,
 * identical on every device regardless of fps.
 */
export class WordBuffer {
  constructor(pauseMs) {
    this._words = [];
    this._pause = pauseMs;
    this._lastAddAt = 0;
  }

  /** Append a detected sign; returns it, or null for empty. */
  add(word, nowMs) {
    if (!word) return null;
    this._words.push(word);
    this._lastAddAt = nowMs;
    return word;
  }

  /** Check the inactivity clock; auto-clear after the pause window. */
  tick(nowMs) {
    if (this._words.length === 0) return;
    if (nowMs - this._lastAddAt >= this._pause) this.clear();
  }

  getText() {
    return this._words.join(" ");
  }

  clear() {
    this._words.length = 0;
    this._lastAddAt = 0;
  }
}
