"""
Word / moving-sign model training (J, Z, hola, adios...).

Each sample holds 126 features = mean(63) + std(63) of a 20-frame normalized
sequence. This encodes both the static shape and the movement.

Input:
    CSVs generated by capture/capture_words.py

Output:
    model/model_words.h5
    model/labels_words.json

Usage:
    1. Capture data:  python capture/capture_words.py
    2. Add the path to DATA_CSVS in this script
    3. Train:         python training/train_words.py
"""

import json
import os
import sys

import numpy as np
import pandas as pd
from sklearn.metrics import classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.utils.class_weight import compute_class_weight

import tensorflow as tf
from tensorflow.keras import callbacks, layers, models, regularizers

# -------------------------------------------------------------------
# Configuration — add here your CSVs captured with capture_words.py.
# Can be a single path (str) or a list of paths (list).
# -------------------------------------------------------------------

DATA_CSVS = [
    "data/real_capture/words/words_20260521_175252_hola.csv",
    "data/real_capture/words/words_20260521_215226_hola--2.csv",
    "data/real_capture/words/words_20260601_195842_adios.csv",
    "data/real_capture/words/words_20260601_200315_adios--2.csv",
    "data/real_capture/words/words_20260520_222047_nada.csv",
    "data/real_capture/words/words_20260521_213259_yo.csv",
]

MODEL_OUT  = "model/model_words.h5"
LABELS_OUT = "model/labels_words.json"

BATCH_SIZE = 32
EPOCHS     = 300
NOISE_STD  = 0.008   # noise on the temporal features
L2         = 1e-4
SEED       = 42

# Mirror mask for 126 features (mean_x0..z20 + std_x0..z20).
# Negate the X coordinates in both halves (mean and std of x).
_MIRROR_MASK_126 = tf.constant(
    [-1.0 if i % 3 == 0 else 1.0 for i in range(126)],
    dtype=tf.float32,
)


def _load_data(csvs) -> tuple[np.ndarray, np.ndarray]:
    paths = [csvs] if isinstance(csvs, str) else csvs
    frames = []
    for p in paths:
        if p and os.path.isfile(p):
            frames.append(pd.read_csv(p))
            print(f"  + {len(frames[-1]):,} samples from {p}")
        elif p:
            print(f"  [WARN] File not found: {p}")
    if not frames:
        print("[ERROR] No CSV found. Check DATA_CSVS.")
        raise SystemExit(1)
    df = pd.concat(frames, ignore_index=True)
    labels = np.array(df["label"].tolist())
    X = df.drop(columns=["label"]).to_numpy(dtype=np.float32)
    return X, labels


def _augment(x, y):
    x = x + tf.random.normal(tf.shape(x), mean=0.0, stddev=NOISE_STD)
    flip = tf.random.uniform(()) > 0.5
    x = tf.cond(flip, lambda: x * _MIRROR_MASK_126, lambda: x)
    return x, y


def _build_dataset(x, y, training):
    ds = tf.data.Dataset.from_tensor_slices((x, y))
    if training:
        ds = ds.shuffle(buffer_size=len(x), seed=SEED, reshuffle_each_iteration=True)
        ds = ds.map(_augment, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.batch(BATCH_SIZE).prefetch(tf.data.AUTOTUNE)
    return ds


def _build_model(input_dim, num_classes):
    inputs = layers.Input(shape=(input_dim,), name="temporal_features")

    x = layers.Dense(256, activation="relu", kernel_regularizer=regularizers.l2(L2))(inputs)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(128, activation="relu", kernel_regularizer=regularizers.l2(L2))(x)
    x = layers.BatchNormalization()(x)
    x = layers.Dropout(0.3)(x)

    x = layers.Dense(64, activation="relu", kernel_regularizer=regularizers.l2(L2))(x)
    x = layers.BatchNormalization()(x)

    outputs = layers.Dense(num_classes, activation="softmax", name="prediction")(x)

    model = models.Model(inputs, outputs, name="word_classifier")
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=1e-3),
        loss="sparse_categorical_crossentropy",
        metrics=["accuracy"],
    )
    return model


def main():
    np.random.seed(SEED)
    tf.random.set_seed(SEED)

    if not DATA_CSVS or all(not p for p in DATA_CSVS):
        print("[ERROR] Add at least one CSV to DATA_CSVS.")
        print("  1. Capture data: python capture/capture_words.py")
        print("  2. Add the generated path to DATA_CSVS in this script.")
        sys.exit(1)

    print("Loading data...")
    X, y_str = _load_data(DATA_CSVS)
    print(f"  {X.shape[0]:,} samples  x  {X.shape[1]} features")

    if X.shape[0] < 20:
        print(f"[ERROR] Only {X.shape[0]} samples. Capture more data before training.")
        sys.exit(1)

    # Stratified 80/20 split
    try:
        X_train, X_val, y_train_str, y_val_str = train_test_split(
            X, y_str, test_size=0.2, stratify=y_str, random_state=SEED,
        )
    except ValueError:
        X_train, X_val, y_train_str, y_val_str = train_test_split(
            X, y_str, test_size=0.2, random_state=SEED,
        )

    encoder = LabelEncoder()
    y_train = encoder.fit_transform(y_train_str)

    val_mask  = np.isin(y_val_str, encoder.classes_)
    X_val     = X_val[val_mask]
    y_val_str = y_val_str[val_mask]
    y_val     = encoder.transform(y_val_str) if len(y_val_str) > 0 else np.array([], dtype=np.int32)

    num_classes = len(encoder.classes_)
    print(f"  Classes ({num_classes}): {', '.join(encoder.classes_)}")
    print(f"  Train: {len(X_train):,}  Val: {len(X_val):,}\n")

    weights = compute_class_weight("balanced", classes=np.arange(num_classes), y=y_train)
    class_weight = {i: float(w) for i, w in enumerate(weights)}

    train_ds = _build_dataset(X_train, y_train, training=True)
    val_ds   = _build_dataset(X_val, y_val, training=False) if len(y_val) > 0 else None

    print("Building model...")
    model = _build_model(input_dim=X_train.shape[1], num_classes=num_classes)
    model.summary()

    monitor = "val_accuracy" if val_ds else "accuracy"
    cb = [
        callbacks.EarlyStopping(monitor=monitor, patience=30,
                                restore_best_weights=True, verbose=1),
        callbacks.ReduceLROnPlateau(monitor=monitor, factor=0.6,
                                    patience=10, min_lr=1e-6, verbose=1),
        callbacks.ModelCheckpoint(MODEL_OUT, monitor=monitor,
                                  save_best_only=True, verbose=0),
    ]

    print("\nTraining...\n")
    model.fit(
        train_ds,
        validation_data=val_ds,
        epochs=EPOCHS,
        callbacks=cb,
        class_weight=class_weight,
        verbose=2,
    )

    model.save(MODEL_OUT)

    print("\n" + "=" * 60)
    if val_ds is not None:
        val_loss, val_acc = model.evaluate(val_ds, verbose=0)
        print(f"  val_loss:     {val_loss:.4f}")
        print(f"  val_accuracy: {val_acc:.4f}  ({val_acc * 100:.2f} %)")
    print("=" * 60)

    if len(y_val) > 0:
        y_pred = np.argmax(model.predict(X_val, verbose=0), axis=1)
        labels_in_val = np.unique(y_val)
        names_in_val  = [encoder.classes_[i] for i in labels_in_val]
        print("\nPer-class report:")
        print(classification_report(y_val, y_pred,
                                    labels=labels_in_val,
                                    target_names=names_in_val,
                                    digits=3, zero_division=0))

    labels_dict = {str(i): name for i, name in enumerate(encoder.classes_)}
    with open(LABELS_OUT, "w", encoding="utf-8") as f:
        json.dump(labels_dict, f, indent=2, ensure_ascii=False)

    print(f"Model saved to:  {MODEL_OUT}")
    print(f"Labels saved to: {LABELS_OUT}")
    print("\nWord training complete.")


if __name__ == "__main__":
    main()
